# Uncomment the next line to define a global platform for your project
 #platform :ios, '13.0'

target 'Refeezy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Refeezy

  pod 'IQKeyboardManagerSwift'
  #pod 'IQKeyboardManager'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'Kingfisher'
  pod 'NVActivityIndicatorView'
  pod 'SwiftMessages'
  pod 'NotificationBannerSwift'
  pod 'Firebase'
  pod 'FirebaseMessaging'
  pod 'netfox'
  pod 'MoyasarSdk', git: 'https://github.com/moyasar/moyasar-ios-pod.git'

  target 'RefeezyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RefeezyUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
